#Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Aditya Gupta
tagline:          'CSE Student'
description:      'ML enthusiast - specifically the bridge between practical applications and theoretical possibilities. I work on interesting projects and research.'
url:              http:adityagupta961.github.io
baseurl:          /

author:
  name:           'Aditya Gupta'
  url:            https://linkedin.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/adityagupta961/adityagupta961.github.io
