# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Aditya Gupta
tagline:          'Computer Science Engineering Student'
description:      'Computer Science Engineering Student trying to become a software engineer.'
url:              www.adityagupta961.github.io
baseurl:          /

author:
  name:           'Aditya Gupta'
  url:            https://linkedin.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/AdityaGupta961
